name: test (zig target)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: install nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Write dev.zon
      uses: "DamianReeves/write-file-action@master"
      with:
          path: src/dev.zon
          write-mode: overwrite
          contents: |
            .{
                .api_id = 1,
                .api_hash = "1",
                .bot_token = "a:b",
            }

    - name: run tests
      shell: 'nix develop -c bash -e {0}'
      run: zig build --summary all test
    - name: build
      shell: 'nix develop -c bash -e {0}'
      run: zig build